package com.deliveryplatform.domain.entity;

public enum FinancialOperationType {
    OPENING_BALANCE,
    ORDER_DELIVERED,
    COD_COLLECTED,
    COD_REMITTED,
    MERCHANT_SETTLEMENT,
    DRIVER_EARNING,
    AGENCY_COMMISSION,
    PLATFORM_REVENUE,
    WITHDRAWAL_RESERVATION,
    WITHDRAWAL_PAID,
    WITHDRAWAL_FAILED,
    PAYOUT_REQUESTED,
    PAYOUT_PAID,
    REFUND_CREATED,
    ADJUSTMENT_CREATED,
    REVERSAL
}
