import os
import re

directory = '/home/mohamed/CargoLink_VF/frontend/src/pages/agency'

replacements = {
    # Wallet / General
    r"Portefeuille Agence": "Agency Wallet",
    r"Validez les remises COD, pilotez les soldes et préparez les paiements marchands": "Validate COD remittances, manage balances and prepare merchant payments",
    r"Compte gelé": "Account Frozen",
    r"Rafraîchir": "Refresh",
    r"Exporter CSV": "Export CSV",
    r"Exportation...": "Exporting...",
    r"Solde disponible": "Available Balance",
    r"Montant prêt pour les virements et validations": "Amount ready for payouts and validations",
    r"Remises en attente": "Pending Remittances",
    r"Cash déjà collecté mais pas encore validé": "Cash already collected but not yet validated",
    r"Commission du mois": "Commission this month",
    r"Ce que l'agence a déjà sécurisé ce mois-ci": "What the agency has secured this month",
    r"Vue d'ensemble": "Overview",
    r"Commissions": "Commissions",
    r"Remises COD": "COD Remittances",
    r"Virements": "Payouts",
    r"Solde Disponible": "Available Balance",
    r"Total Commissions": "Total Commissions",
    r"Commission en Attente": "Pending Commission",
    r"Ce mois-ci": "This month",
    r"Commissions du mois": "Commission this month",
    r"Cash en attente de validation": "Cash pending validation",
    r"remise\(s\) driver à confirmer": "driver remittance(s) to confirm",
    r"Total dû aux marchands": "Total due to merchants",
    r"Montant COD collecté moins la commission agence": "COD amount collected minus agency commission",
    r"Taux de Commission": "Commission Rate",
    r"de chaque frais de livraison": "of each delivery fee",
    r"Total collecté COD": "Total collected COD",
    r"Remises COD en Attente": "Pending COD Remittances",
    r"Confirmez la réception physique du cash": "Confirm physical receipt of cash",
    r"Alerte": "Alert",
    r"Aucune remise en attente": "No pending remittances",
    r"Confirmer": "Confirm",
    r"Historique des Commissions": "Commission History",
    r"Rechercher un ordre...": "Search an order...",
    r"Tout": "All",
    r"En attente": "Pending",
    r"Crédité": "Credited",
    r"Aucune commission": "No commission",
    r"Statut": "Status",
    r"Date": "Date",
    r"sur": "of",
    r"Flux des Remises COD": "COD Remittances Flow",
    r"Total": "Total",
    r"Aucune remise reçue": "No remittance received",
    r"Livreur": "Driver",
    r"Montant": "Amount",
    r"Colis": "Parcels",
    r"Actions": "Actions",
    r"Demande de Virement": "Payout Request",
    r"Disponible": "Available",
    r"Compte de paiement": "Payment Account",
    r"Aucun compte PayPal actif": "No active PayPal account",
    r"Les virements agence utilisent le compte PayPal connecté côté backend.": "Agency payouts use the PayPal account connected on the backend.",
    r"Compte gelé — virements bloqués": "Frozen account — payouts blocked",
    r"E-mail PayPal": "PayPal Email",
    r"Annuler": "Cancel",
    r"Connecter PayPal": "Connect PayPal",
    r"Compte PayPal requis avant de demander un virement.": "PayPal account required before requesting a payout.",
    r"Connecter un compte PayPal": "Connect a PayPal account",
    r"Montant \(MAD\)": "Amount (MAD)",
    r"Destination": "Destination",
    r"Le backend enregistrera ce compte via son `paymentAccountId`.": "The backend will save this account via its `paymentAccountId`.",
    r"Demander le virement": "Request Payout",
    r"Historique des Virements": "Payouts History",
    r"Aucun virement effectué": "No payout made",
    r"Compte": "Account",
    r"Échec du chargement des données de rapprochement": "Failed to load reconciliation data",
    r"Rapport PDF": "PDF Report",
    r"Toutes les commandes": "All orders",
    r"Livrées": "Delivered",
    r"En transit": "In transit",
    r"Échouées": "Failed",
    r"N° de Suivi": "Tracking No",
    r"Destinataire": "Receiver",
    r"Montant COD": "COD Amount",
    r"Paiement": "Payment",
    r"Aucune donnée de rapprochement trouvée": "No reconciliation data found",
    r"Approbations des livreurs": "Driver Approvals",
    r"Vérifiez et validez les nouveaux livreurs rattachés à votre agence.": "Check and validate new drivers attached to your agency.",
    r"Aucun livreur en attente d'approbation": "No driver pending approval",
    r"Chargement du portefeuille...": "Loading wallet...",
    r"Échec de l'export": "Export failed",
    r"Erreur lors de la confirmation": "Error during confirmation",
    r"Remise confirmée — solde crédité": "Remittance confirmed — balance credited",
    r"Demande de virement soumise": "Payout request submitted",
    r"Échec de la demande": "Request failed",
    r"Compte PayPal connecté": "PayPal account connected",
    r"Impossible de connecter le compte PayPal": "Failed to connect PayPal account",
    r"Montant minimum": "Minimum amount",
    r"Solde insuffisant": "Insufficient balance",
    r"Compte PayPal requis": "PayPal account required",
    r"E-mail PayPal requis": "PayPal email required",
    r"Agence introuvable": "Agency not found",
    r"Rechercher par N° de suivi, client ou adresse...": "Search by tracking no, customer or address...",
    r"Rechercher par N° de suivi ou nom de client...": "Search by tracking no or customer name...",
    r"Statuts": "Statuses",
    r"Localisation": "Location",
    r"Type": "Type",
    r"Tous les Statuts": "All Statuses",
    r"Plage de Dates": "Date Range",
    r"Total COD Analysé": "Total COD Analyzed",
    r"Total Missions": "Total Missions",
    r"Auditez et exportez les flux locaux de paiement à la livraison": "Audit and export local Cash-on-Delivery flows",
    r"Livré": "Delivered",
    r"Annulé": "Cancelled",
    r"Cette commande est en attente d'assignation.": "This order is pending assignment.",
    r"Réglé": "Settled",
    r"En attente COD": "Pending COD",
    r"Initialisation des paramètres...": "Initializing settings...",
    r"Profil de l'Agence": "Agency Profile",
    r"Gérez l'identité de l'agence et les infos de contact.": "Manage agency identity and contact info.",
    r"Paramètres de l'Agence": "Agency Settings",
    r"Rechercher par nom, plaque ou téléphone...": "Search by name, plate or phone...",
}

for root, _, files in os.walk(directory):
    for file in files:
        if file.endswith('.tsx') or file.endswith('.ts'):
            filepath = os.path.join(root, file)
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
            
            new_content = content
            for fr, en in replacements.items():
                new_content = re.sub(fr, en, new_content, flags=re.IGNORECASE)
                
            if new_content != content:
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(new_content)
                print(f"Translated: {filepath}")

